git:
  depth: 5
language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: pedre87@gmail.com
  on:
    branch: master
  api_key:
    secure: NMwNZwsWo5ZmH6Mt3vXinILg/lUd49iJtoaVc9k3O3nKvOiZIfKfDku6e67nEtvB7SrwIliTQDtHqiEQuunxhIGl8zYU+c1onQdhKz2PZ59stl/ya4j+93qw/fxiuFjQv0vG1ETkoFHwoC/bHhEfQF+oHTvjX0fN2TZVyKmN0DVM642TquKZFzX3GRa6KF8NZ99CdkatgLRYbaNIsHMDpuCjnvXX14F1J9wgMjI6lHvH2abLawz/IxBfTQfbK+RZnaugMhuQLeknhAi5B6I6xriel0Ixvs1AATTVUqLvBu/QJflcSYFCIVTrnQP7CWS8lIOW4JyR0T7K9UFjA6rVlTJq5kAWeaiCF0HB7YSXf9Szx4NTsGc6LF5NpJgsGF1fo9RvKvb8IK6SUwaUzjcjCaCVTEVr0wc5D59ikgme0bMI8MR0VW4/NtVSHawi44nyUvTPuanp/iNA+S57+3XYWAhaipskAeg5hNEcdtNs0tKDaIE/0fEbeRGwLvj4SHgVZVGC1wqoQ3Z6sBKyMRN6NmvS0XI6B/pU/n6LWsUz6/BJB4nORfgzosxTUk3l4BloSSoeDZyU1DDTUsPzEZnKGX9NRnHu0aISsrfSJiQVGfyaR0wFMDHgnZJ0HoHmrIuI6+t76Ru1njUmwnC0pqkhF8ccpu4pF1WIhQ0336XzEQo=
script:
- nohup yarn test
